#!/usr/bin/env python3

import sys
import os

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__))+"/base")
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__))+"/models")

from event import event

#_____________________________________________________________________________
if __name__ == "__main__":

    #name of config file from command line argument
    args = sys.argv
    if len(args) < 2:
        print("No configuration specified.")
        quit()
    args.pop(0)
    config = args.pop(0)

    #init and run
    event(config)


