
[main]

#beam-gas background

Ee = 9 ; energy of electron beam, GeV

emin = 0.00001 ; minimal photon energy, GeV

model = "beam-gas" ; parametrization

#lattice and pressure data
#from: https://indico.bnl.gov/event/10974/contributions/51260/
lattice_txt = "../../lattice/esr/esr-ir6-100-10.txt"
pressure_xlsx = "../../lattice/chamber/Detector_chamber_210813.xlsx"
pressure_sheet = "H2 only, 10000Ahrs"
pressure_usecols = "B,C"
pressure_skiprows = 12
pressure_nrows = 100

#beam emittance
eps_x = 20e-9 ; m
eps_y = 1.3e-9 ; m

#number of events to generate
nev = 10

#output file name
nam = "bg_9GeV"

write_hepmc_root = true
#write_tx = true



